import os
import sys
from pathlib import Path

def create_dummy_copybooks(target_dir):
    """
    Creates empty dummy copybooks for known missing files to bypass analysis errors.
    """
    target_path = Path(target_dir).resolve()
    if not target_path.exists():
        print(f"Error: Directory not found: {target_path}")
        sys.exit(1)

    # List of missing copybooks identified from previous logs
    missing_copybooks = [
    ]

    print(f"Creating/Fixing copybooks in: {target_path}")
    
    created_count = 0
    skipped_count = 0
    fixed_count = 0

    for copybook_name_raw in missing_copybooks:
        # Remove extension if present to handle consistently
        base_name = copybook_name_raw.split('.')[0]
        
        # Target: lowercase .cpy (seems to be what smojol wants)
        target_file = target_path / f"{base_name}.cpy"
        
        # Possible source: uppercase .CPY
        source_upper = target_path / f"{base_name}.CPY"
        
        if target_file.exists():
            print(f"  [SKIP] {target_file.name} (already exists)")
            skipped_count += 1
            continue

        if source_upper.exists():
            # Copy content from upper to lower
            try:
                content = source_upper.read_text(encoding='utf-8', errors='ignore')
                target_file.write_text(content, encoding='utf-8')
                print(f"  [FIX] Created {target_file.name} from {source_upper.name}")
                fixed_count += 1
            except Exception as e:
                print(f"  [ERROR] Failed to copy {source_upper.name} to {target_file.name}: {e}")
        else:
            # Create dummy
            try:
                # Create empty file with valid COBOL comment (fixed format: 6 spaces then *)
                with open(target_file, 'w') as f:
                    f.write("      * DUMMY COPYBOOK GENERATED BY ANTIGRAVITY\n")
                print(f"  [CREATE] Created dummy {target_file.name}")
                created_count += 1
            except Exception as e:
                print(f"  [ERROR] Failed to create {target_file.name}: {e}")

    print(f"---------------------------------------------------")
    print(f"Finished. Created Dummies: {created_count}, Fixed Case: {fixed_count}, Skipped: {skipped_count}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 create_dummy_copybooks.py <path_to_cics_dir>")
        sys.exit(1)
    
    create_dummy_copybooks(sys.argv[1])
